name: Workflow - build/push
on:
    push:
	branches:
	    - master

jobs:
    test:
	runs-on: ubuntu-latest
	steps:
	    - uses: actions/checkout@v2
	    - name: Executando testes
	      run:
		docker build . --file Dockerfile
